import type { NextPage, NextComponentType } from "next";
import Head from "next/head";
import Image from "next/image";
import { useWindowSize } from 'usehooks-ts'
import { useEffect, useRef, useState } from "react"

const Home: NextPage = () => {
  const titleRef = useRef<HTMLHeadingElement|null>(null);
  const pagesRef = useRef(null);
  const svgRef = useRef(null);

  let titleH = 0;
  let titleW = 0;

  const [titleDimens, setTitleDimens] = useState<null | [number, number]>(null);

  useEffect(() => {
    if (titleRef.current) {
      console.log(titleRef);
      const titleW = titleRef.current.offsetWidth;
      const titleH = titleRef.current.offsetHeight;
      setTitleDimens([titleW, titleH]);
    }
  },[titleRef.current]);

  let ellipsex = 0;
  let ellipsey = 0;
  if (titleDimens) {
   ellipsex = titleDimens[0];
   ellipsey = titleDimens[1];
  }
  
  return (
    <div>
      <Head>
        <title>Ibrahim Abotaleb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <div className="min-w-[100wh] h-[100vh] grid grid-cols-2">
          <div className="flex-1 mr-2 boxcent h-[100%] w-[100%]" ref={titleRef}>
            <svg className="behind" ref={svgRef} width="50%" height={"" + (100 / 6) + "%"}>
            </svg>
            <h1 className="title boxcent h-[100%] w-[100%]">Ibrahim Abotaleb</h1>
          </div>
          <div className="grid boxcent grid-row-4 ml-3 mt-[25vh] mb-[25vh] items" ref={pagesRef}>
            <a>About</a>
            <a>Resume</a>
            <a>Projects</a>
            <a>Design Portfolio</a>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;