import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {

  let t = Math.random() * 500;
  let interp = t/3 + ";" + t + ";" + t/3;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="behind">
          <svg width="100%" height="100%">
            {/* <circle cx="100" cy="100" r="200" fill="yellow">
              <animate attributeName="r" values={interp} dur="25s" repeatCount="indefinite"></animate>
            </circle>
            
            <circle cx="300" cy="400" r={t} fill="yellow"/> */}
          </svg>
        </div>
        <div className="min-w-[100wh] h-[100vh] grid grid-cols-2">
          <div className="flex-1 mr-2">
            <h1 className="title boxcent h-[100%] w-[100%]">Ibrahim Abotaleb</h1>
          </div>
          <div className="grid boxcent grid-row-4 ml-3 mt-[25vh] mb-[25vh] items">
            <p>About</p>
            <p>Resume</p>
            <p>Projects</p>
            <p>Design Portfolio</p>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
